### ISSUE TITLE
大兄弟打开串口的“9600”和发送数据的“[0x00,0x01,0x02,0x03,0x05]”是固定的吗？

### ISSUE THREAD

**Issue by showtan001** [Marcello168/react-native-SerialPort#4]
打开串口
import RNSerialPort from 'react-native-serial-port';
// TODO: 打开串口
RNSerialPort.openSerialPort('/dev/ttySO', 9600);
发送数据
import RNSerialPort from 'react-native-serial-port';
let byteData = [0x00,0x01,0x02,0x03,0x05]
// TODO: 发送数据
RNSerialPort.sendByteData(byteData);

还有串口状态true、false是什么意思
串口回传数据（[13, 10, 43, 67, 83, 81, 58, 32, 50, 53, 44, 57, 57, 13, 10, 13, 10, 79, 75, 13, 10]）这些数组又代表神马

**Comment by Mase9527** [comment]
串口状态 是串口打开是否成功

**Comment by Mase9527** [comment]
> 打开串口
> import RNSerialPort from 'react-native-serial-port';
> // TODO: 打开串口
> RNSerialPort.openSerialPort('/dev/ttySO', 9600);
> 发送数据
> import RNSerialPort from 'react-native-serial-port';
> let byteData = [0x00,0x01,0x02,0x03,0x05]
> // TODO: 发送数据
> RNSerialPort.sendByteData(byteData);
> 
> 还有串口状态true、false是什么意思
> 串口回传数据（[13, 10, 43, 67, 83, 81, 58, 32, 50, 53, 44, 57, 57, 13, 10, 13, 10, 79, 75, 13, 10]）这些数组又代表神马
串口发送数据和接收数据 是要根据你们的硬件协议来写的

**Comment by showtan001** [comment]
> > 打开串口
> > import RNSerialPort from 'react-native-serial-port';
> > // TODO: 打开串口
> > RNSerialPort.openSerialPort('/dev/ttySO', 9600);
> > 发送数据
> > import RNSerialPort from 'react-native-serial-port';
> > let byteData = [0x00,0x01,0x02,0x03,0x05]
> > // TODO: 发送数据
> > RNSerialPort.sendByteData(byteData);
> > 还有串口状态true、false是什么意思
> > 串口回传数据（[13, 10, 43, 67, 83, 81, 58, 32, 50, 53, 44, 57, 57, 13, 10, 13, 10, 79, 75, 13, 10]）这些数组又代表神马
> > 串口发送数据和接收数据 是要根据你们的硬件协议来写的




> > 打开串口
> > import RNSerialPort from 'react-native-serial-port';
> > // TODO: 打开串口
> > RNSerialPort.openSerialPort('/dev/ttySO', 9600);
> > 发送数据
> > import RNSerialPort from 'react-native-serial-port';
> > let byteData = [0x00,0x01,0x02,0x03,0x05]
> > // TODO: 发送数据
> > RNSerialPort.sendByteData(byteData);
> > 还有串口状态true、false是什么意思
> > 串口回传数据（[13, 10, 43, 67, 83, 81, 58, 32, 50, 53, 44, 57, 57, 13, 10, 13, 10, 79, 75, 13, 10]）这些数组又代表神马
> > 串口发送数据和接收数据 是要根据你们的硬件协议来写的

大兄弟，这个支持”M102 型售货机控制卡（[https://wenku.baidu.com/view/8ea2c786b207e87101f69e3143323968001cf416.html](url)）“吗？就是Android控制售货的柜机，我看文档上面读取ID是”00 09 00 000000000000000000000000000000A7 B6“这么一长串
